def get_coarse_labels(dataset_name):
    if dataset_name == "CIFAR100":
        # CIFAR100 coarse labels - needed for plotting examples
        coarse_label = [
                        'apple',  # id 0
                        'aquarium_fish',
                        'baby',
                        'bear',
                        'beaver',
                        'bed',
                        'bee',
                        'beetle',
                        'bicycle',
                        'bottle',
                        'bowl',
                        'boy',
                        'bridge',
                        'bus',
                        'butterfly',
                        'camel',
                        'can',
                        'castle',
                        'caterpillar',
                        'cattle',
                        'chair',
                        'chimpanzee',
                        'clock',
                        'cloud',
                        'cockroach',
                        'couch',
                        'crab',
                        'crocodile',
                        'cup',
                        'dinosaur',
                        'dolphin',
                        'elephant',
                        'flatfish',
                        'forest',
                        'fox',
                        'girl',
                        'hamster',
                        'house',
                        'kangaroo',
                        'computer_keyboard',
                        'lamp',
                        'lawn_mower',
                        'leopard',
                        'lion',
                        'lizard',
                        'lobster',
                        'man',
                        'maple_tree',
                        'motorcycle',
                        'mountain',
                        'mouse',
                        'mushroom',
                        'oak_tree',
                        'orange',
                        'orchid',
                        'otter',
                        'palm_tree',
                        'pear',
                        'pickup_truck',
                        'pine_tree',
                        'plain',
                        'plate',
                        'poppy',
                        'porcupine',
                        'possum',
                        'rabbit',
                        'raccoon',
                        'ray',
                        'road',
                        'rocket',
                        'rose',
                        'sea',
                        'seal',
                        'shark',
                        'shrew',
                        'skunk',
                        'skyscraper',
                        'snail',
                        'snake',
                        'spider',
                        'squirrel',
                        'streetcar',
                        'sunflower',
                        'sweet_pepper',
                        'table',
                        'tank',
                        'telephone',
                        'television',
                        'tiger',
                        'tractor',
                        'train',
                        'trout',
                        'tulip',
                        'turtle',
                        'wardrobe',
                        'whale',
                        'willow_tree',
                        'wolf',
                        'woman',
                        'worm',
                    ]
    elif dataset_name == "CIFAR10":
        # CIFAR10 coarse labels
        coarse_label=[
                        'airplane',
                        'automobile',
                        'bird',
                        'cat',
                        'deer',
                        'dog',
                        'frog',
                        'horse',
                        'ship',
                        'truck'
                    ]
    elif dataset_name == "EMNIST":
        # EMNIST labels
        coarse_label=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
                      'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
                      'U', 'V', 'W', 'X', 'Y', 'Z',
                      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
                      'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                      'u', 'v', 'w', 'x', 'y', 'z']
    elif dataset_name == "MNIST":
        # MNIST labels
        coarse_label = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    elif dataset_name == "FashionMNIST":
        #FashionMNIST labels
        coarse_label=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']
    elif dataset_name == "smallNORB":
        # smallNORB labels
        coarse_label = ['airplanes', 'cars', 'four-legged animals', 'human figures', 'trucks']
    elif dataset_name == "GTSRB":
        # GTSRB labels
        coarse_label = ['20_speed',
                        '30_speed',
                        '50_speed',
                        '60_speed',
                        '70_speed',
                        '80_speed',
                        '80_lifted',
                        '100_speed',
                        '120_speed',
                        'no_overtaking_general',
                        'no_overtaking_trucks',
                        'right_of_way_crossing',
                        'right_of_way_general',
                        'give_way',
                        'stop',
                        'no_way_general',
                        'no_way_trucks',
                        'no_way_one_way',
                        'attention_general',
                        'attention_left_turn',
                        'attention_right_turn',
                        'attention_curvy',
                        'attention_bumpers',
                        'attention_slippery',
                        'attention_bottleneck',
                        'attention_construction',
                        'attention_traffic_light',
                        'attention_pedestrian',
                        'attention_children',
                        'attention_bikes',
                        'attention_snowflake',
                        'attention_deer',
                        'lifted_general',
                        'turn_right',
                        'turn_left',
                        'turn_straight',
                        'turn_straight_right',
                        'turn_straight_left',
                        'turn_right_down',
                        'turn_left_down',
                        'turn_circle',
                        'lifted_no_overtaking_general',
                        'lifted_no_overtaking_trucks']
    else:
        raise ValueError("No coarse_label found for dataset " + str(dataset_name))
    return coarse_label
#indices for CIFAR10, CIFAR100,
# image_indices = [2,3,6,7]

#indices for MNIST
#image_indices = [6,7,10,15]

#indices for EMNIST
#image_indices = [11,52,12,31]